# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- eventstore

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2.401'
  inputs:
    packageType: sdk
    version: 2.2.401
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: ShellScript@2
  displayName: 'Run domain tests'
  inputs:
    scriptPath: 'backend/cli/local-run_domain_tests.sh'
    #args: '' # Optional
    #disableAutoCwd: false # Optional
    cwd: 'backend/cli'
    #failOnStandardError: false
- task: ShellScript@2
  displayName: 'Run unit tests'
  inputs:
    scriptPath: 'backend/cli/local-run_unit_tests.sh'
    #args: '' # Optional
    #disableAutoCwd: false # Optional
    cwd: 'backend/cli'
    #failOnStandardError: false
- task: ShellScript@2
  displayName: 'Run integration tests'
  inputs:
    scriptPath: 'backend/cli/docker-run_integration_tests.sh'
    #args: '' # Optional
    #disableAutoCwd: false # Optional
    cwd: 'backend/cli'
    #failOnStandardError: false
- task: ShellScript@2
  displayName: 'Run functional tests'
  inputs:
    scriptPath: 'backend/cli/docker-run_functional_tests.sh'
    #args: '' # Optional
    #disableAutoCwd: false # Optional
    cwd: 'backend/cli'
    #failOnStandardError: false
