trigger:
- ci-update

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2.401'
  inputs:
    packageType: sdk
    version: 2.2.401
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  inputs:
    command: test
    publishTestResults: true
    testRunTitle: 'Domain unit tests'
    restoreDirectory: backend/src/Core.DomainModelTests
    workingDirectory: backend/src/Core.DomainModelTests
- task: DotNetCoreCLI@2
  inputs:
    command: test
    publishTestResults: true
    testRunTitle: 'Infrastructure unit tests'
    restoreDirectory: backend/src/UnitTests
    workingDirectory: backend/src/UnitTests
- task: ShellScript@2
  displayName: 'Run integration tests'
  inputs:
    scriptPath: 'backend/cli/docker-run_integration_tests.sh'
    cwd: 'backend/cli'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '*.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)'
- task: ShellScript@2
  displayName: 'Run functional tests'
  inputs:
    scriptPath: 'backend/cli/docker-run_functional_tests.sh'
    cwd: 'backend/cli'
